### ISSUE TITLE
src/_getinfo_test.cpp が通っていない

### ISSUE THREAD

**Issue by fushihara** [xtne6f/TvtPlay#3]
[他プラグインに情報提供するウィンドウメッセージを追加 · xtne6f/TvtPlay@865dbab](https://github.com/xtne6f/TvtPlay/commit/865dbab9d8949ad8fa116fda2b41a98babc2da16)

を自コードで試してみたのですが、どうも動かない。
src/_getinfo_test.cpp のコードを追いかけてみると、

```
static DWORD MySendMessage(HWND hwnd, UINT msg, WPARAM wParam = 0, LPARAM lParam = 0)
{
	// プラグインから呼ぶ場合はSendMessageでOK
	DWORD_PTR dwpResult = 0;
	if (SendMessageTimeout(hwnd, msg, wParam, lParam, SMTO_NORMAL, 5000, &dwpResult) ) {
		return (DWORD)dwpResult;
	}
	return 0;
}
```

の、SendMessageTimeoutが常に(最初のWM_TVTP_GET_MSGVER等)0を返していました。
どの値も取れない状態になっているのですが、これはこちらの環境に問題があるのでしょうか。
お手数ですが、作者様の環境で動作するか確認をお願い致します。

```
	// 複数起動している場合は最初に見つかったものが返る
	HWND hwnd = FindTvtPlayFrame();
	if (!hwnd) {
		_tprintf(TEXT("TvtPlayが見つかりません。\n"));
		return 0;
	}
```

直前の、tvtPlayを探す処理は正常に動いていました。

こちらの環境はwindows10 64bit、上記コードのデバッグはvisual studio 2015 Communityで試しました

**Comment by xtne6f** [comment]
確認してみましたが、現時点のmaster(=work)およびwork-plusとも動作しました。
TvtPlayが見つかった上でGET_MSGVERが0を返す場合に考えられるのは、
この情報取得機能を追加したのがver.2.1からなので、それ以前のTvtPlayでは0が返ります。
あと、情報取得側とTvtPlayの実行権限が違う場合(TVTestを管理者権限で実行など)は0が返るかもしれません。

**Comment by fushihara** [comment]
ありがとうございます。タスクマネージャーで確認した所、tvtestが管理者特権＝はい で実行していました。
