### ISSUE TITLE
予約開始タイミングで自動的にpipe経由でTVTestを起動した後に一連の録画終了時に自動的にTVTestを閉じる

### ISSUE THREAD

**Issue by kouhgithub** [xtne6f/TvtPlay#6]
「予約開始タイミングで自動的にpipe経由でTVTestを起動した後に一連の録画終了時に自動的にTVTestを閉じる」選択肢もあればいいとは思うのですが
こういう依頼ってTvtPlayで依頼すればいいのかEDCBのほうで依頼すればいいのかどっちがいいんでしょうか

「再生終了時にTVTestを閉じる」ではpipe経由で再生終了時にTVTestが自動では閉じませんでした

**Comment by xtne6f** [comment]
EDCBでもいいですがこっちでもいいです。
まだ深く考えてないんですが「BonDriver_Pipe(やUDPやTCP)を使用している間に一定時間データを受信しなければTVTestを閉じる」TVTestのプラグインを作るとうまくいくんじゃないかと思いました。
EDCBに限らずわりと応用が利きそうなのでちょっと試してみます。

**Comment by xtne6f** [comment]
結局EDCBの「Viewボタン」機能を発展させるのがシンプルで妥当と考えたため、こちらの[EDCBのフォーク](https://github.com/xtne6f/EDCB)にて、視聴時以外の条件でのViewボタンに割り当てたアプリの起動、EpgDataCap_Bon終了時のViewの同時終了などにより要望を実現できるようにしました。

**Comment by kouhgithub** [comment]
対応ありがとうございます
