### ISSUE TITLE
再生時のプレイリストを表示するポップアップにスクロールバーを

### ISSUE THREAD

**Issue by tookunozima** [xtne6f/TvtPlay#7]
表題の件につきまして、
ポップアップで表示されるプレイリストの件数が大量にある場合、
現状の上下ボタンではかなり押し続けないと先のファイルにまで到達できません。
スクロールバーなどの配置をお願いしたいです。
またポップアップで表示されるコントロール(『現在のファイルを前へ移動』など)も埋もれてしまっていますので、
コントロール群は下部固定になると利便性がよくなるかと思います。
下ボタンの配置は最後のファイル名辺りに付けるようにして、
なるべく現状の機能は残しつつ変更いただけると幸いです。

![TvtPlay_playlist_scroll_03](https://github.com/xtne6f/TvtPlay/assets/122070984/9be2fec3-0f39-4c68-a1c7-8dcf228c8f8c)
![TvtPlay_playlist_scroll_04](https://github.com/xtne6f/TvtPlay/assets/122070984/04d69d8f-c666-4df9-a5f3-3bf82a3413a2)

**Comment by xtne6f** [comment]
OSの標準のポップアップを利用している都合でスクロールバーは実装が大変なので、30件ごと(件数は調整可能)にサブメニュー化する方向で検討しています ( [work-candidateブランチ]( https://github.com/xtne6f/TvtPlay/tree/work-candidate ) ) がいかがでしょうか？
こんな感じでマウスで一気に手繰れます。
![popup](https://github.com/xtne6f/TvtPlay/assets/2673799/a2b5d546-c970-411d-90d7-23b641429b48)

**Comment by tookunozima** [comment]
スクロールバーの実装面での難しさに思い至らず要望してしまいましたが、
別の形で実現できそうだとご提案いただきありがとうございます。
確かにその方法なら目的は達成できそうです。
是非進めていただければと思います。

**Comment by xtne6f** [comment]
上のものでリリースとしました。
結果的にデフォルトの最大30件表示だと表示しきれない場合に対応することもできました、提案感謝します。

**Comment by tookunozima** [comment]
Releaseされた3.1について、
遅くなりましたが、100件超でも問題なく動いていることを確認しました。
これまで通していたデザインとして一貫性あるかというと悩ましいのが本音なのですが、
以前より一覧性やファイルの見つけやすさは格段に上がっていて十二分に助かっているところです。
重ねてありがとうございました。
