### ISSUE TITLE
読み込み共有モードで開けた動画の追っかけ再生の挙動について

### ISSUE THREAD

**Issue by Tokman5** [xtne6f/TvtPlay#8]
録画サーバーはLinux(Ubuntu Server LTS 24.04)+EDCB(tkntrec版)
Sambaを通じてWindowsマシンから録画ファイルにアクセスし、TvtPlay 32を使用して視聴
smb.confでoplocksを無効にしています

上記の環境で録画中のファイルを開いた場合、追っかけ再生自体はできます（ファイルを開いた時点より後の映像や音声が視聴できる）が、
総再生時間が増えないという現象が起こり、更に
- 追っかけ再生時につくはずの総再生時間の横の+マークが無い
- カレントポジションが総再生時間を越えた地点でのシークが正常にできない
- 総再生時間を越えるとレジューム地点の保存が行われない

等といった、想定通りではない挙動が引き起こされます。

原因はTsSender.cppのCTsSender::Open関数の挙動にあると思われます。
https://github.com/xtne6f/TvtPlay/blob/aca077bdabb06bb40b3f8b9911d259bf7222eb8f/src/TsSender.cpp#L210-L221
Sambaを通じてアクセスしているからなのか、録画中のファイルでも読み込み共有モードで開けてしまいます（else節を設けてメッセージボックスを出すように改変するとそのダイアログが表示されました。また常に書き込み共有モードで開くように改変すると正しい挙動で追っかけ再生されています）。
また動画の長さ情報の更新時などにも、追っかけ再生かどうかの判定にm_file->IsShareWrite()が使用されており、上記のような現象に繋がっていると思われます。

録画中のファイルであるかどうかの判定ロジックやIsShareWrite()が使われている部分等に変更を加えて、より多様な環境で正しく追っかけ再生が行えるようになれば幸いです。

**Comment by xtne6f** [comment]
ありがとうございます（返信遅れましてすみません）。

推察のとおりOpenまわりの問題のようです。
oplockのほうは他に手がないか試してみたのですが、やはりsmb.confで無効にするしかなさそうです。
`veto oplock files = /*.ts/` などで拡張子の限定は可能ですが…
(こちらの環境は Debian 12.8 (bookworm) samba 2:4.17.12+EDCB(work+s-241110))

共有ドライブでの追っかけ再生は「なんだかうまく動かない」という判断で半ば諦めていたのですが、これで一定程度利用可能になりそうです。

**Comment by Tokman5** [comment]
更新ありがとうございます
b155b7ae9f2e183b5c8b024583e014e471538402 を試すと追っかけ再生が上手くできるようになりました。
ソースの変更内容的に録画中でないファイルを開いた時も追っかけ再生の挙動になる（数秒の間、総再生時間の表示が増え続けてから元の長さに戻る等）のを確認しましたが、表示以外に大きな問題は無いように思います。

**Comment by xtne6f** [comment]
確認ありがとうございます。
ファイルを開いてから3秒間ほど総再生時間が増える挙動は、やはり見た目が気になるので c1e3d6d2c463634eb68aefb95096693e184e1741 で調整しました。
共有ドライブのファイルでは総再生時間の隣に追っかけ再生(かもしれないこと)を示す`+`マークが3秒間だけ表示されますが、総再生時間の増分はしなくなりました。
